/*INSERT INTO USER (USERNAME, PASSWORD) VALUES ('pranav', 'password');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('user', 'foobar');
*/

/*INSERT INTO USER (USERNAME, PASSWORD) VALUES ('pranav', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('user', '$2a$11$3NO32OV1TGjap3xMpAEjmuiizitWuaSwUYz42aMtlxRliwJ8zm4Sm');*/


INSERT INTO USER (USERNAME, PASSWORD) VALUES ('pranav', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('user', '$2a$11$3NO32OV1TGjap3xMpAEjmuiizitWuaSwUYz42aMtlxRliwJ8zm4Sm');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('pranav', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('pranav', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
